stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: "terraform/end-to-end-3tier-app-deployment/terraform-3tier-image-platform"
  TF_VERSION: "1.5.0"
  TF_VAR_aws_region: "eu-north-1"
  TF_VAR_environment: "dev"
  TF_VAR_project_name: "hsbc-gamma-dev"

cache:
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}
  - terraform init

terraform-fmt:
  stage: validate
  script:
    - terraform fmt -check -recursive

terraform-validate:
  stage: validate
  script:
    - terraform validate

terraform-plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
  only:
    - merge_requests
    - main

terraform-apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  only:
    - main
  when: manual

terraform-apply-dev:
  stage: apply
  script:
    - terraform apply -auto-approve
  only:
    - develop
  when: manual